### PR TITLE
clang-asan: use clang 19 as CRAN does

### PR DESCRIPTION
**Pull request by pachadotdev**
Dear Gabor,

I hope you are doing well!

This container does the same as CRAN's CLAN-ASAN/UBSAN check, which they currently do with R-devel, Fedora 36 and Clang 19.

The image is built in two steps, or otherwise instead of 4GB, it would be 15GB.

I hope it's useful.

### CODE REVIEW

**Comment by gaborcsardi** [comment]
Thanks! We already have an image for clang-asan, so clearly you think that this one is better? How is it better?

**Comment by pachadotdev** [comment]
> Thanks! We already have an image for clang-asan, so clearly you think that this one is better? How is it better?

not really better, it does the same but differently

CRAN uses a different OS and Clang version compared to your image, and the improvement of this one is using a configuration that is extremely close to the CRAN setup (the difference is that the Docker image uses a slightly more recent R-devel)

I think it's useful to check corner cases. In any case, I adapted from the Ubuntu-clang image that is already available.

**Comment by gaborcsardi** [comment]
Do you know of any packages that have failures that the current crang-asan container misses?

**Comment by pachadotdev** [comment]
> Do you know of any packages that have failures that the current crang-asan container misses?

redatam :(

it was removed

**Comment by pachadotdev** [comment]
this is a long shot, but I have no idea where to ask for assistance with this error

https://github.com/pachadotdev/open-redatam/actions/runs/11767478085/job/32776199717

I asked here https://stackoverflow.com/questions/79171799/addresssanitizer-error-alloc-dealloc-mismatch-operator-new-vs-free-in-r-packa?noredirect=1#comment139613374_79171799 and got -4

**Comment by gaborcsardi** [comment]
> redatam

The messaging is slightly different, but that does reproduce for me, at the same example:
https://github.com/r-hub2/intravert-uncrystallised-groundhog-redatam/actions/runs/11769187104/job/32779895794

**Comment by pachadotdev** [comment]
> > redatam
> 
> The messaging is slightly different, but that does reproduce for me, at the same example: https://github.com/r-hub2/intravert-uncrystallised-groundhog-redatam/actions/runs/11769187104/job/32779895794

thanks!

actually this is one of the few useful messages I got when I asked

do have any idea of how to fix this?

**Comment by gaborcsardi** [comment]
These are memory errors, you'd have to debug them. I can't say what the problem is, especially that I don't know this codebase at all.

**Comment by gaborcsardi** [comment]
Wrt. this PR, while it is better to have a system closer to CRAN, I think for clang-asan it is more important to match the compiler than the distro, so we could update clang to 19, that should be very easy.

The PR is not ideal for a number of reasons:
- Building clang from source is very slow.
- A 4 GB image is still pretty big, even the current container that is 2.87 GB is big.
- I would prefer not to use Fedora 36, which was EOL more than a year ago, even if CRAN uses that.
- I don't have libc++ builds for system dependencies on Fedora 36, like we do for Ubuntu at https://github.com/r-hub/repos-ppa.
- I am not building binary packages for Fedora 36 libc++, like I do for current clang-asan, at https://github.com/r-hub/repos#ubuntu-2204--r-devel--libc-ubuntu-2204-r45-libc, so package checks would be very slow.

I am sorry if this sounds negative, it is actually great to have your PR, it might be useful in the future if we indeed need clang from source on Fedora. But right now it feels like it is better to keep the current image, or possibly update it to clang19.

**Comment by pachadotdev** [comment]
> Wrt. this PR, while it is better to have a system closer to CRAN, I think for clang-asan it is more important to match the compiler than the distro, so we could update clang to 19, that should be very easy.
> 
> The PR is not ideal for a number of reasons:
> 
>     * Building clang from source is very slow.
> 
>     * A 4 GB image is still pretty big, even the current container that is 2.87 GB is big.
> 
>     * I would prefer not to use Fedora 36, which was EOL more than a year ago, even if CRAN uses that.
> 
>     * I don't have libc++ builds for system dependencies on Fedora 36, like we do for Ubuntu at https://github.com/r-hub/repos-ppa.
> 
>     * I am not building binary packages for Fedora 36 libc++, like I do for current clang-asan, at https://github.com/r-hub/repos#ubuntu-2204--r-devel--libc-ubuntu-2204-r45-libc, so package checks would be very slow.
> 
> 
> I am sorry if this sounds negative, it is actually great to have your PR, it might be useful in the future if we indeed need clang from source on Fedora. But right now it feels like it is better to keep the current image, or possibly update it to clang19.

the "median solution" about using clang19 sounds great

let me edit this to use the APT in Ubuntu image, which creates a very thin image

**Comment by pachadotdev** [comment]
@gaborcsardi Hi. I updated the clang-asan image to clang v19, which gives the same results as CRAN-asan, and it is much lighter than building from source with Fedora

**Comment by gaborcsardi** [comment]
Great, thank you!

**Pull request merged**
